module.exports = {
  error: {
    DUPLICATE_ORDER: "A heading with this order already exists for this assessment.",
    RECORDID_ALREADY_EXISTS: "recordId already exists",
    ALREADY_EXISTS: 'Record already exists',
    DOESNT_EXISTS: 'Record doesn\'t exists',
    INVALID_SHEET_HEADERS: 'invalid/missing headers in file',
    LOG_DOESNT_EXIST: 'Log doesnt exist',
    SERVER: 'Internal Error',
    BAD_REQUEST: 'Bad Request',
    UNAUTHORIZED: 'Unauthorized',
    INVALID_OTP: 'OTP is invalid.',
    USER_NOT_EXIST: "User doesn't exist.",
    USER_NOT_ACTIVE: 'User account is deactivated. Please contact admins.',
    INVALID_CREDENTIAL: 'Please enter valid credentials.',
    INVALID_JWT_TOKEN: 'Token is invalid.',
    INVALID_FILE: 'File is of not valid type.',
    INVALID_EMAIL: 'Invalid email',
    USER_NOT_VERIFIED: 'User not verified.',
    USER_DEACTIVATED: 'User deactivated.',
    ADMIN_USER_NOT_EXIST: "Admin User doesn't exists.",
    USER_ROLE_EXISTS: 'Role is associated to users',
    USER_MEMBERSHIP_EXISTS: 'Membership is associated to users',
    SATELLITE_LIMIT: 'Your subscription only allows for one set of satellite reports.  Please upgrade to get weekly reports.',
    USER_TYPE_NOT_EXITS: "User type doesn't exists.",
    USER_LOCKED: 'User locked.',
    OTP_EXPIRE: 'OTP expired.',
    USER_EXIST_ALREADY: 'User already exists with email or mobile',
    EMAIL_EXIST_ALREADY: 'User already exist with this email.',
    EMAIL_AND_MOBILE_EXIST_ALREADY: 'User already exist with this email and mobile.',
    ORGANIZATION_CODE_DOESNOT_EXIST: 'Organization code doesnot exist.',
    INVALID_MOBILE_NO: 'Invalid mobile number',
    MOBILE_EXIST_ALREADY: 'User already exist with this mobile number.',
    UNVERIFIED_MOBILE_NOT_AVAILABLE:
      'Unverified mobile number is not available. Please update your profile.',
    COUNTRY_CODE_NOT_AVAILABLE:
      'Country code is not available for this user. Please update your profile.',
    ALREADY_VERIFIED: 'Verified already.',
    DOCUMENT_NOT_EXIST: "Document doesn't exist.",
    DOCUMENT_PRESENT_INSIDE_FOLDER:
      'Folder contains other files/folder within, please move them or delete them before deleting this folder.',
    NO_TOKEN: 'No token, authorization denied.',
    NO_DATA: 'No data available.',
    NOT_FOUND: 'Not found.',
    EQUIPMENT_EXIST_ALREADY: 'Equipment already exist.',
    NOT_UNIQUE: 'Not unique.',
    NOT_UNIQUE_FARMNAME_AND_REGISTRATIONNO:
      'Not unique farm name and registration number together.',
    FERTILIZER_EXIST_ALREADY: 'Fertilizer already exist.',
    FARM_EXIST_ALREADY: 'A farm with this name already exists. Please try a different name.',
    ERROR_WHILE_PROCESSING: 'Quantity exceeds than the available',
    PURCHASE_ORDER_NOT_FOUND: 'Purchase order not found',
    BATCH_PROCESSING_MANAGEMENT: 'Batch processing not found',
    INVALID_INPUT:"Invalid Input",

    code: {
      BAD_REQUEST: 400,
      UNAUTHORIZED: 401,
      NOT_FOUND: 404,
      FORBIDDEN: 403,
      SERVER_ERROR: 500,
      CONFLICT: 409,
      UNPROCESSABLE_ENTITY: 422,
      USER_NOT_VERIFIED: 452
    },
    EQUIPMENT_FUEL_RECORD_MISSING: "Missing required fields in fuel records data",
    EQUIPMENT_MODE_OF_OPERATION_EXISTS: 'Mode of operation already exists.',
    EQUIPMENT_MODE_OF_OPERATION_NOT_FOUND: 'Mode of operation not found.',
    EQUIPMENT_GROUP_EXISTS: 'Equipment Group already exists.',
    EQUIPMENT_GROUP_NOT_FOUND: 'Equipment group not found.',
    EQUIPMENT_NAME_EXISTS: 'Equipment Name already exists.',
    EQUIPMENT_NAME_NOT_FOUND: 'Equipment Name not found.',
    EQUIPMENT_ALREADY_EXISTS_FOR_ACTIVITY:
      'Equipment Name already exists for provided activity.',
    CROP_ASSOCIATED_TO_FARM: 'Unable to delete,crops associated to this farm exists in records.',

    EQUIPMENT_EXISTS: 'Equipment already exists.',
    EQUIPMENT_NOT_FOUND: 'Equipment not found.',
    FOLDER_ALREADY_EXISTS: 'Folder with name already exists.',
    FOLDER_NOT_FOUND: 'Folder doesnot exist.',
    FILE_ALREADY_EXISTS_IN_FOLDER: 'File already exists in the folder.',
    DOCUMNET_DOESNOT_EXIST: 'Document doesnot exist.',
    DOCUMNET_FOLDER_CANNOT_BE_MOVED: 'Folders cannot be moved.',
    IRRIGATION_WATER_SOURCE_EXISTS: 'Irrigation water source already exist.',
    IRRIGATION_TYPE_EXISTS: 'Irrigation type already exist.',
    IRRIGATION_STAGE_EXISTS: 'Irrigation stage already exist.',
    CROP_STORAGE_METHOD_EXISTS: 'Crop storage method already exist.',
    CROP_STORAGE_TYPE_EXISTS: 'Crop storage type already exist.',
    IRRIGATION_SCHEDULE_EXISTS: 'Irrigation schedule already exist.',
    IRRIGATION_WATER_SOURCE_ORIGIN_EXISTS:
      'Irrigation water source origin already exist.',
    IRRIGATION_WATER_SOURCE_DOESNOT_EXISTS:
      'Irrigation water source doesnot exist.',
    IRRIGATION_DATA_DOESNOT_EXISTS: 'Irrigation data doesnot exist.',
    HARVESTING_DATA_DOESNOT_EXISTS: 'Harvesting data does not exist.',
    HARVESTING_METHOD_EXISTS: 'Harvesting method data already exist. ',
    CROP_STORAGE_DOESNOT_EXISTS: 'Crop storage doesnot exist.',
    IRRIGATION_WATER_SOURCE_ORIGIN_DOESNOT_EXISTS:
      'Irrigation water source origin doesnot exist.',
    CROP_OBSERVATION_DOESNOT_EXIST: 'Crop observation doesnot exist.',
    REPORT_DATA_DOESNOT_EXISTS: 'Report data does not exist.',
    INVALID_USERTYPE: 'Invalid userType',
    REPORTS_ALREADY_IN_PROGRESS:
      'New report requests can be submitted after completing current report requests',
    TOPIC_NAME_NOT_FOUND: 'Name cannot be null',
    TOPIC_DISPLAY_NAME_NOT_FOUND: 'Display Name cannot be null',
    TARGET_EXIST: "Target for this year is already set!!",
    TARGET_NOT_FOUND: "Target Not found",
    RESET_PASSWORD: "Reset Your Password",
    SETTINGS_DOESNT_EXIST: "Report settings doesnt exist",
    INVALID_FERTILIZER_NAME: "Fertilizer name is invalid",
    INVALID_CHEMICAL_NAME: "Chemical name is invalid",
    INVALID_PESTICIDE_NAME: "Pesticide name is invalid",
    AREA_TOO_LARGE: "Area too Large. Maximum area limit is 1000 hectares",
    CARBON_CREDIT_PROJECT_NOT_FOUND: 'Failed to find carbon credit project with id',
    CARBON_CREDIT_PROJECT_AGREEMENT_MISSING: "Missing required values",
    CARBON_CREDIT_PROJECT_NOT_EXISTS: "Carbon credit project does not exist!",
    CARBON_CREDIT_FARM_NOT_EXISTS: "Farm does not exist!",
    CARBON_CREDIT_CROP_NOT_EXISTS: "Crop does not exist!",
    CARBON_CREDIT_CROP_NO_VARIETY: "No crop varieities provided with crop",
    CARBON_CREDIT_CROP_VARIETY_NOT_EXISTS: "Crop variety does not exist",
    CARBON_CREDIT_EQUIPMENT_NOT_EXISTS: "Equipment does not exist!",
    CARBON_CREDIT_EQUIPMENT_FUEL_RECORD_NOT_EXISTS: "Equipment fuel record does not exist!",
    CARBON_CREDIT_SOWING_NOT_EXISTS: "Sowing does not exist!",
    CARBON_CREDIT_SEEDLING_NOT_EXISTS: "Seedling does not exist!",
    CARBON_CREDIT_FERTILIZER_NOT_EXISTS: "Fertilizer does not exist!",
    CARBON_CREDIT_AGREEMENT_NOT_EXISTS: "Carbon credit project agreement does not exist!",
    CARBON_CREDIT_S3_UPLOAD_ERROR: "Failed to upload signed document to s3, please try again!",
    CARBON_CREDIT_CROP_GROWING_EQUIPMENT_NOT_EXISTS: "Could not find the record for crop growing equipment with the given id!"
  },
  success: {
    CARBON_CREDIT_CROP_GROWING_CROP_CREATED: "Carbon credit crop growing crops successfully created!",
    CARBON_CREDIT_CROP_GROWING_EQUIPMENT_CREATED: "Carbon credit crop growing equipments successfully created!",
    CARBON_CREDIT_CROP_GROWING_CREATED: "Carbon credit project farm crops growing successfully created!",
    CARBON_CREDIT_PROJECTS_LAND_TITLE_PERMIT_UPLOADED: "Carbon credit land title/permit uploaded successfully",
    CARBON_CREDIT_PROJECTS_AGREEMENT_UPDATED: "Carbon credit project farm updated successfully",
    CARBON_CREDIT_PROJECTS_CREATED: "Carbon credit project farm created successfully",
    CARBON_CREDIT_PROJECTS_FETCHED: 'Fetched carbon credit projects successfully',
    CARBON_CREDIT_PROJECT_FETCHED: 'Fetched specific carbon credit project',
    CARBON_CREDIT_SDGS_FETCHED: 'Fetched Sustainable Development Gaols Successfully',
    ESG_ASSESSMENT_CREATED: 'ESG Assessment created successfully',
    ESG_ASSESSMENT_UPDATED: 'ESG Assessment updated successfully',
    PRE_REGISTERD: 'Pre registered successfully',
    PARCHMENT_ADDED: 'Parchment out saved successfully',
    CUPPING: 'Cupping saved successfully',
    INBOUND_CUPPING: 'Inbound cupping saved successfully',
    OUTBOUND_CUPPING: 'Outbound cupping saved successfully',
    NOTIFICATION_CREATED: 'notification has been created successfully',
    ACTIVATION_MAIL_SENT: 'activation email is sent successfully',
    UPLOADED: 'uploaded successfully',
    SOIL_AUDIT_CREATED: 'Soil audit has been created successfully',
    WEED_UPDATED: 'Weed has been updated successfully',
    WEED_DELETED: 'Weed has been deleted successfully',
    WEED_CREATED: 'Weed has been created successfully',
    WEED_METHOD_CREATED: 'Weed method has been created successfully',
    WEED_STAGE_CREATED: 'Weed stage has been created successfully',
    WEED_TYPE_CREATED: 'Weed type has been created successfully',
    PLANTING_TYPE_CREATED: 'Sowing type has been created successfully',
    SOWING_UPDATED: 'Sowing has been updated successfully',
    SOWING_DELETED: 'Sowing has been deleted successfully',
    SOWING_CREATED: 'Sowing has been created successfully',
    SOILPREP_ACTIVITY_CREATED: 'Soil preparation activity has been created',
    PRACTICE_UPDATED: 'Practice has been updated',
    PRACTICE_DELETED: 'Practice has been deleted successfully',
    PRACTICE_CREATED: 'Practice has been created successfully',
    GOAL_DELETED: 'goal has been deleted successfully.',
    CROPHISTORY_UPDATED: 'user crop history has been updated successfully.',
    GOAL_UPDATED: 'user goals has been updated successfully.',
    CROP_TYPE_CREATED: 'crop type has been created successfully.',
    CROP_VARIETY_CREATED: 'crop variety has been created successfully.',
    CROP_REGISTERED: 'crop has been registered successfully.',
    CROP_REGISTERED_UPDATED: 'crop has been updated successfully.',
    CROP_REGISTERED_DELETED: 'crop has been deleted successfully.',
    CONFIGURATION_SAVED: 'Configuration are saved successfully.',
    FARM_SEGMENT_UPDATED: 'Farm segment is updated successfully.',
    FARM_SEGMENT_CREATED: 'Farm segment is created successfully.',
    REGISTERED: 'Inserted successfully.',
    INSERTED: 'Inserted successfully.',
    SAVED: 'saved successfully.',
    UPDATED: 'updated successfully',
    DELETED: 'Deleted successfully.',
    USER_DELETED:'User Deleted Successfully',
    COMMUNITY_INVITATION_SENT: 'Invitation message is sent successfully.',
    OTP_MATCH: 'OTP matches successfully.',
    PASSWORD_CREATED: 'Password created successfully.',
    OTP_SENT: 'OTP sent successfully.',
    PROFILE_UPDATED: 'profile updated successfully.',
    ROLE_UPDATED: 'Role updated successfully.',
    LOGIN: 'Logged in successfully.',
    LOGOUT: 'Logged out successfully',
    FARM_ADDED: 'Farm added successfully.',
    FETCH: 'Fetched successfully.',
    NO_RESPONSE: 'No data found.',
    USER_DOC_UPLOADED: 'User documents has been uploaded successfully.',
    PROFILE_FETCHED: 'Profile data has been fetched successfully.',
    MOBILE_VERIFIED: 'Mobile number is verified successfully.',
    EMAIL_VERIFIED: 'Email is verified successfully.',
    DOC_UPDATED: 'Document updated successfully.',
    SHIPMENT_CREATED: 'Shipment created successfully.',
    SHIPMENT_UPDATED: 'Shipment updated successfully.',
    PROFILE_PIC_UPDATED: 'Profile Picture updated successfully.',
    GEOFENCE_ADDED: 'Geofencing added successfully.',
    PLANTING_ADDED: 'Planting Data added successfully.',
    ACCESSTOKEN_GENERATED: 'Accesstoken genereated successfully.',
    INSERTED: 'Inserted successfully.',
    CROP_INFO_UPDATED: 'Crop information updated successfully.',
    AUDIT_RESPONSE_SAVED: 'Audit response is saved successfully.',
    HARVESTING_ADDED: 'You have successfully added  harvesting Information ',
    HARVEST_METHOD_CREATED: 'You have successfully added  harvesting method ',
    HARVEST_DELETED: 'Harvesting is removed successfully.',
    HARVERST_UPDATED: 'Harvesting data updated successfully.',
    SOILPREPARATIONDATA_ADDED: 'Soil preparation data saved successfully.',
    USER_FARM_EQUIPMENT_ADDED: 'User farm equipment is added successfully.',
    OWNERSHIP_CHANGED:
      'Your request for changing ownership is added successfully.',
    USER_FARM_CROP_ADDED: 'Crop is added successfully into farm.',
    UPDATED: 'Updated successfully.',
    GOAL_ADDED: 'Goal has been added successfully.',
    IS_UNIQUE: 'It is unique',
    code: {
      INFORMATION: 100,
      OK: 200,
      CREATED: 201,
      NO_RESPONSE: 204,
      NOT_MODIFIED: 304,
    },
    EQUIPMENT_MODE_OF_OPERATION_ADDED:
      'Mode of operation for equipment is added successfully.',
    EQUIPMENT_MODE_OF_OPERATION_UPDATED:
      'Mode of operation for equipment is updated successfully.',
    EQUIPMENT_MODE_OF_OPERATION_DELETED:
      'Mode of operation for equipment is removed successfully.',
    EQUIPMENT_GROUP_ADDED: 'Equipment Group is added successfully.',
    EQUIPMENT_GROUP_UPDATED: 'Equipment Group is updated successfully.',
    EQUIPMENT_GROUP_DELETED: 'Equipment Group is removed successfully.',
    EQUIPMENT_NAME_ADDED: 'Equipment Name is added successfully.',
    EQUIPMENT_NAME_UPDATED: 'Equipment Name is updated successfully.',
    EQUIPMENT_NAME_DELETED: 'Equipment Name is removed successfully.',
    EQUIPMENT_ADDED: 'Equipment is added successfully.',
    EQUIPMENT_UPDATED: 'Equipment is updated successfully.',
    EQUIPMENT_DELETED: 'Equipment is removed successfully.',
    LIVESTOCK_ADDED: 'Livestock is added successfully.',
    DOCUMENT_CREATED: 'Document is created successfully.',
    DOCUMENT_NAME_UPDATED: 'Document renamed successfully.',
    DOCUMENT_MOVED_SUCCESS: 'Document moved successfully.',
    DOCUMENT_DELETED_SUCCESS: 'Document deleted successfully.',
    IRRIGATION_WATER_SOURCE_CREATED:
      'Irrigation water source added successfully.',
    IRRIGATION_TYPE_CREATED: 'Irrigation type added successfully.',
    IRRIGATION_WATER_SOURCE_ORIGIN_CREATED:
      'Irrigation water source origin added successfully.',
    IRRIGATION_STAGE_CREATED: 'Irrigation stage added successfully.',
    CROP_STORAGE_METHOD_CREATED: 'Crop storage method added successfully.',
    CROP_STORAGE_TYPE_CREATED: 'Crop storage type added successfully.',
    IRRIGATION_SCHEDULE_CREATED: 'Irrigation schedule added successfully.',
    IRRIGATION_DATA_CREATED: 'Irrigation data has been added successfully.',
    CROP_STORAGE_CREATED: 'Crop storage data has been added successfully.',
    CROP_STORAGE_UPDATED: 'Crop storage data has been updated successfully.',
    IRRIGATION_DATA_UPDATED: 'Irrigation data has been updated successfully.',
    IRRIGATION_DATA_DELETED: 'Irrigation data has been deleted successfully.',
    CROP_STORAGE_DATA_DELETED:
      'Crop storage data has been deleted successfully.',
    CROP_OBSERVATION_CREATED:
      'Crop observation data has been added successfully.',
    CROP_OBSERVATION_UPDATED:
      'Crop observation data has been updated successfully.',
    CROP_OBSERVATION_REMOVED:
      'Crop observation data has been removed successfully.',
    ADMIN_USER_STATUS_UPDATE: 'Status has been updated successfully.',
    USER_UPDATED: 'User updated successfully.',
    MODULE_PERMISSION_UPDATED:
      'Modules permission has been updated successfully.',
    ADMIN_USER_CREATED: 'Admin User has been created successfully.',
    REPORT_ADDED: 'Report added successfully.',
    REPORT_DELETED: 'Report is removed successfully.',
    REPORT_UPDATED: 'Report data updated successfully.',
    REPORT_ALREADY_CREATED: 'Report is already Generated.',
    PROFILE_AUTHENTICATION_SETTINGS_UPDATED:
      "Profile authentication settings has been updated successfully.",
    USERCOUNT_FETCH_SUCCESS: "User count fetched successfully.",
    SOILMANAGEMENTDATA_ADDED: "Soil management data saved successfully.",
    SOILMANAGEMENTDATA_DELETED: "Soil management data deleted successfully.",
    SOILMANAGEMENTDATA_UPDATED: "Soil management data updated successfully.",
    PEST_MANAGEMENT_DATA_ADDED: "Pest management data saved successfully.",
    PEST_MANAGEMENT_DATA_UPDATED: "Pest management data updated successfully.",
    PEST_MANAGEMENT_DATA_DELETED: "Pest management data deleted successfully.",
    DISEASE_MANAGEMENT_DATA_ADDED: "Disease management data saved successfully.",
    DISEASE_MANAGEMENT_DATA_UPDATED: "Disease management data updated successfully.",
    DISEASE_MANAGEMENT_DATA_DELETED: "Disease management data deleted successfully.",
    DISEASE_ADDED: "Disease has been added successfully",
    DISEASE_DELETED: "Disease has been deleted successfully",
    DISEASE_UPDATED: "Disease has been updated successfully",
    USERCOUNT_FETCH_SUCCESS: 'User count fetched successfully.',
    SOILMANAGEMENTDATA_ADDED: 'Soil management data saved successfully.',
    SOILMANAGEMENTDATA_DELETED: 'Soil management data deleted successfully.',
    SOILMANAGEMENTDATA_UPDATED: 'Soil management data updated successfully.',
    PEST_MANAGEMENT_DATA_ADDED: 'Pest management data saved successfully.',
    PEST_MANAGEMENT_DATA_UPDATED: 'Pest management data updated successfully.',
    PEST_MANAGEMENT_DATA_DELETED: 'Pest management data deleted successfully.',
    NUTRIENT_MANAGEMENT_DATA_ADDED: 'Nutrient management data saved successfully.',
    NUTRIENT_MANAGEMENT_DATA_UPDATED: 'Nutrient management data updated successfully.',
    NUTRIENT_MANAGEMENT_DATA_DELETED: 'Nutrient management data deleted successfully.',
    TARGET_ADDED: "Target saved successfully",
    TARGET_UPDATED: "Target updated successfully",
    WEATHER_SETTING_ADDED: "Weather setting saved successfully.",
    WEATHER_SETTING_FETCHED: "Weather Setting fetched successfully.",
    WEATHER_SETTING_DELETED: "Weather Setting deleted successfully.",
    WEATHER_SETTING_UPDATED: "Weather Setting updated successfully.",
    STORAGE_SETTING_ADDED: "Storage setting saved successfully.",
    STORAGE_SETTING_FETCHED: "Storage Setting fetched successfully.",
    STORAGE_SETTING_DELETED: "Storage Setting deleted successfully.",
    STORAGE_SETTING_UPDATED: "Storage Setting updated successfully.",
    CURRENCY_SETTING_ADDED: "Currency setting saved successfully.",
    CURRENCY_SETTING_FETCHED: "Currency Setting fetched successfully.",
    CURRENCY_SETTING_DELETED: "Currency Setting deleted successfully.",
    CURRENCY_SETTING_UPDATED: "Currency Setting updated successfully.",
    FARMER_ADDED_SUCCESSFULLY: "Farmer added successfully.",

    UNIT_CATEGORY_ADDED:'Unit category successfully added',
    UNIT_CATEGORY_UPDATED:'Unit category successfully added',
    UNIT_CATEGORY_LIST:'Unit categories',
    UNIT_CATEGORY:'Unit category',
    UNIT_CATEGORY_DELETED:'Unit Category Deleted',

    UNIT_LIST_ADDED:'Unit list successfully added',
    UNIT_LIST_UPDATED:'Unit list successfully added',
    UNIT_LIST_LIST:'Unit lists',
    UNIT_LIST:'Unit List',
    UNIT_LIST_DELETED:'Unit list Deleted',

    LIST:'List Data',

  },
  message: {
    COMMUNITY_INVITATION:
      'You are invited to join the [COMMUNITY_NAME] community. Consider clicking on the link below to proceed. Invite Link: [LINK]',
  },
};
