const { check, query } = require('express-validator');

exports.validateCreateTreeMappingPlot = () => {
    return [
        check('request_id')
            .optional()
            .isUUID().withMessage('Tree mapping request ID must be a valid UUID'),
        check('plot_no')
            .optional() // Plot number is optional as it can be generated by the backend
            .isString().withMessage('Plot number must be a string'),
        check('country')
            .optional()
            .isString().withMessage('Country must be a string'),
        check('project_name')
            .optional()
            .isString().withMessage('Project name must be a string'),
        check('latitude')
            .optional()
            .isDecimal().withMessage('Latitude must be a decimal'),
        check('longitude')
            .optional()
            .isDecimal().withMessage('Longitude must be a decimal'),
        check('radius')
            .optional()
            .isDecimal().withMessage('Radius must be a decimal'),
        check('notes')
            .optional()
            .isString().withMessage('Notes must be a string'),
        check('slope')
            .optional()
            .isDecimal().withMessage('Slope must be a decimal'),
        check('aspect')
            .optional()
            .isDecimal().withMessage('Aspect must be a decimal'),
        check('no_of_trees')
            .optional()
            .isInt().withMessage('Number of trees must be an integer'),
        check('status')
            .optional()
            .isIn(['pending', 'partially_submitted', 'submitted']).withMessage('Status must be one of: pending, partially_submitted, submitted'),
        check('trees')
            .optional()
            .isArray().withMessage('Trees must be an array'),
        check('trees.*.treeName')
            .optional()
            .isString().withMessage('Tree name must be a string'),
        check('trees.*.treeType')
            .optional()
            .isString().withMessage('Tree type must be a string'),
        check('trees.*.diameter_at_breast_height')
            .optional()
            .isFloat().withMessage('Diameter at breast height must be a number'),
        check('trees.*.height')
            .optional()
            .isFloat().withMessage('Height must be a number'),
        check('trees.*.crown_base_height')
            .optional()
            .isFloat().withMessage('Crown base height must be a number'),
        check('trees.*.vigor')
            .optional()
            .isInt().withMessage('Vigor must be an integer')
    ];
};

exports.validateUpdateTreeMappingPlot = () => {
    return [
        check('plot_no')
            .optional()
            .isString().withMessage('Plot number must be a string'),
        check('latitude')
            .optional()
            .isDecimal().withMessage('Latitude must be a decimal'),
        check('longitude')
            .optional()
            .isDecimal().withMessage('Longitude must be a decimal'),
        check('radius')
            .optional()
            .isDecimal().withMessage('Radius must be a decimal'),
        check('notes')
            .optional()
            .isString().withMessage('Notes must be a string'),
        check('slope')
            .optional()
            .isDecimal().withMessage('Slope must be a decimal'),
        check('aspect')
            .optional()
            .isDecimal().withMessage('Aspect must be a decimal'),
        check('no_of_trees')
            .optional()
            .isInt().withMessage('Number of trees must be an integer'),
        check('status')
            .optional()
            .isIn(['pending', 'partially_submitted', 'submitted']).withMessage('Status must be one of: pending, partially_submitted, submitted')
    ];
};
