const cropTypeCountry = [
  { region: "general", code: "general" },
  { region: "Indonesia", code: "ID" },
  { region: "Brazil", code: "BR" },
  { region: "Democratic republic of the Congo", code: "CD" },
  { region: "Nigeria", code: "NG" },
  { region: "Uganda", code: "UG" },
  { region: "Bolivia", code: "BO" },
  { region: "Lybia", code: "LY" },
  { region: "Nepal", code: "NP" },
  { region: "Zambia", code: "ZM" },
  { region: "Colombia", code: "CO" },
  { region: "Canada", code: "CA" },
  { region: "USA", code: "US" },
  { region: "India", code: "IN" },
  { region: "india", code: "IN" },
  { region: "Peru", code: "PE" },
  { region: "Guatemala", code: "GT" },
  { region: "Mexico", code: "MX" },
  { region: "Ethiopia", code: "ET" },
  { region: "colombia", code: "CO" },
  { region: "Vietnam", code: "VN" },
  { region: "Argentina", code: "AR" },
  { region: "Paraguay", code: "PY" },
  { region: "Panama", code: "PA" },
  { region: "Ivory Coast", code: "CI" },
  { region: "Libya", code: "LY" },
  { region: "North America", code: "general" },
  { region: "Egypt", code: "EG" },
  { region: "usa", code: "US" },
  { region: "Sudan", code: "SD" },
  { region: "argentina", code: "AR" },
  { region: "australia", code: "AU" },
  { region: "brazil", code: "BR" },
  { region: "Honduras", code: "HN" },
  { region: "indonesia", code: "ID" },
  { region: "United_States", code: "US" },
  { region: "Australia", code: "AU" },
  { region: "ethopia", code: "ET" },
  { region: " Nigeria ", code: "NG" },
  { region: " Brazil ", code: "BR" },
  { region: "Brazil", code: "BR" },
  { region: " India ", code: "IN" },
  { region: "India", code: "IN" },
  { region: "Nepal", code: "NP" },
  { region: " Ethiopia ", code: "ET" },
  { region: " European Union ", code: "general" },
  { region: "China", code: "CN" },
  { region: "Kenya", code: "KE" },
];

module.exports = {
  cropTypeCountry,
};
