
const { Sequelize } = require('sequelize');
module.exports = {
  development: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    port: process.env.LIVE_PORT || 3306,
    dialect: "mysql",
    logging: process.env.SQL_QUERY_LOG === 'false' ? false: true,
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      handleDisconnects: true,
    acquire: 60000,
      idle: 30000,
      evict: 60000,
    },
    retry: { match: [
        "ConnectionAcquireTimeoutError",
        "SequelizeConnectionAcquireTimeoutError", Sequelize.ConnectionError,
         Sequelize.ConnectionTimedOutError,
    ], max: 5,
},
    timezone: '+00:00'
  },
  staging: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    port: process.env.LIVE_PORT || 3306,
    dialect: "mysql",
    logging: process.env.SQL_QUERY_LOG === 'false' ? false: true,
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      handleDisconnects: true,
    acquire: 60000,
      idle: 30000,
      evict: 60000,    },
      retry: { match: [
        "ConnectionAcquireTimeoutError",
        "SequelizeConnectionAcquireTimeoutError", Sequelize.ConnectionError,
         Sequelize.ConnectionTimedOutError,
    ], max: 5,
},
    timezone: '+00:00'
  },
  pre_prod: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    port: process.env.LIVE_PORT || 3306,
    dialect: "mysql",
    logging: process.env.SQL_QUERY_LOG === 'false' ? false: true,
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      handleDisconnects: true,
    acquire: 60000,
      idle: 30000,
      evict: 60000,    },
      retry: { match: [
        "ConnectionAcquireTimeoutError",
        "SequelizeConnectionAcquireTimeoutError", Sequelize.ConnectionError,
         Sequelize.ConnectionTimedOutError,
    ], max: 5,
},
    timezone: '+00:00'
  },
  production: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    port: process.env.LOCAL_PORT || 3306,
    dialect: "mysql",
    logging: process.env.SQL_QUERY_LOG === 'false' ? false: true,
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      handleDisconnects: true,
    acquire: 60000,
      idle: 30000,
      evict: 60000,    },
      retry: { match: [
        "ConnectionAcquireTimeoutError",
        "SequelizeConnectionAcquireTimeoutError", Sequelize.ConnectionError,
         Sequelize.ConnectionTimedOutError,
    ], max: 5,
},
    timezone: '+00:00'
  },
  uat: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    port: process.env.LOCAL_PORT || 3306,
    dialect: "mysql",
    logging: process.env.SQL_QUERY_LOG === 'false' ? false: true,
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      handleDisconnects: true,
    acquire: 60000,
      idle: 30000,
      evict: 60000,    },
      retry: { match: [
        "ConnectionAcquireTimeoutError",
        "SequelizeConnectionAcquireTimeoutError", Sequelize.ConnectionError,
         Sequelize.ConnectionTimedOutError,
    ], max: 5,
},
    timezone: '+00:00'
  },
  local: {
    username: process.env.LOCAL_USERNAME,
    password: process.env.LOCAL_PASSWORD,
    database: process.env.LOCAL_DB,
    host: process.env.LOCAL_HOST,
    port: process.env.LOCAL_PORT || 3306,
    dialect: "mysql",
    logging: process.env.SQL_QUERY_LOG === 'false' ? false: true,
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      handleDisconnects: true,
    acquire: 60000,
      idle: 30000,
      evict: 60000,    },
      retry: { match: [
        "ConnectionAcquireTimeoutError",
        "SequelizeConnectionAcquireTimeoutError", Sequelize.ConnectionError,
         Sequelize.ConnectionTimedOutError,
    ], max: 5,
},
    timezone: '+00:00'
  },
  stagingLive: {
    username: process.env.STAGING_USERNAME,
    password: process.env.STAGING_PASSWORD,
    database: process.env.STAGING_DB,
    host: process.env.STAGING_HOST,
    port: process.env.STAGING_PORT || 3306,
    dialect: "mysql",
    logging: process.env.SQL_QUERY_LOG === 'false' ? false: true,
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      handleDisconnects: true,
    acquire: 60000,
      idle: 30000,
      evict: 60000,    },
      retry: { match: [
        "ConnectionAcquireTimeoutError",
        "SequelizeConnectionAcquireTimeoutError", Sequelize.ConnectionError,
         Sequelize.ConnectionTimedOutError,
    ], max: 5,
},
    timezone: '+00:00'
  },
  uatLive: {
    username: process.env.UAT_USERNAME,
    password: process.env.UAT_PASSWORD,
    database: process.env.UAT_DB,
    host: process.env.UAT_HOST,
    port: process.env.UAT_PORT || 3306,
    dialect: "mysql",
    logging: process.env.SQL_QUERY_LOG === 'false' ? false: true,
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      handleDisconnects: true,
    acquire: 60000,
      idle: 30000,
      evict: 60000,    },
      retry: { match: [
        "ConnectionAcquireTimeoutError",
        "SequelizeConnectionAcquireTimeoutError", Sequelize.ConnectionError,
         Sequelize.ConnectionTimedOutError,
    ], max: 5,
},
    timezone: '+00:00'
  },
  productionLive: {
    username: process.env.PRODUCTION_USERNAME,
    password: process.env.PRODUCTION_PASSWORD,
    database: process.env.PRODUCTION_DB,
    host: process.env.PRODUCTION_HOST,
    port: process.env.PRODUCTION_PORT || 3306,
    dialect: "mysql",
    logging: process.env.SQL_QUERY_LOG === 'false' ? false: true,
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      handleDisconnects: true,
    acquire: 60000,
      idle: 30000,
      evict: 60000,    },
      retry: { match: [
        "ConnectionAcquireTimeoutError",
        "SequelizeConnectionAcquireTimeoutError", Sequelize.ConnectionError,
         Sequelize.ConnectionTimedOutError,
    ], max: 5,
},
    timezone: '+00:00'
  },
  test: {
    username: process.env.TEST_USERNAME,
    password: process.env.TEST_PASSWORD,
    database: process.env.TEST_DB,
    host: process.env.TEST_HOST,
    port: process.env.TEST_PORT || 3306,
    dialect: "mysql",
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      handleDisconnects: true,
    acquire: 60000,
      idle: 30000,
      evict: 60000,    },
      retry: { match: [
        "ConnectionAcquireTimeoutError",
        "SequelizeConnectionAcquireTimeoutError", Sequelize.ConnectionError,
         Sequelize.ConnectionTimedOutError,
    ], max: 5,
},
    timezone: '+00:00',
    logging: process.env.SQL_QUERY_LOG === 'false' ? false: true,
  },
};
