require('dotenv').config();
module.exports = {
  test: {
    username: 'root',
    password: 'root@123',
    database: 'dimitra_sass',
    host: '127.0.0.1',
    dialect: 'mysql',
  },
  production: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    // port: process.env.LIVE_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: 20,
      min: 0,
      acquire: 60000,
  idle: 30000,
    evict: 60000,    },
  },
  development: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    port: process.env.LIVE_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: 20,
      min: 0,
      acquire: 60000,
  idle: 30000,
    evict: 60000,    },
    dialectOptions: {
      connectTimeout: 30000
    },
    logging: true,
  },

  staging: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    // port: process.env.LIVE_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: 20,
      min: 0,
      acquire: 60000,
  idle: 30000,
    evict: 60000,    },
  },
  uat: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    // port: process.env.LIVE_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: 20,
      min: 0,
      acquire: 60000,
  idle: 30000,
    evict: 60000,    },
  },
  local: {
    username: process.env.LOCAL_USERNAME,
    password: process.env.LOCAL_PASSWORD,
    database: process.env.LOCAL_DB,
    host: process.env.LOCAL_HOST,
    port: process.env.LOCAL_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      acquire: 60000,
    },
    timezone: '+00:00',
    logging: true,
  },
  stagingLive: {
    username: process.env.STAGING_USERNAME,
    password: process.env.STAGING_PASSWORD,
    database: process.env.STAGING_DB,
    host: process.env.STAGING_HOST,
    port: process.env.STAGING_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      acquire: 60000,
    },
    timezone: '+00:00',
  },
  productionLive: {
    username: process.env.PRODUCTION_USERNAME,
    password: process.env.PRODUCTION_PASSWORD,
    database: process.env.PRODUCTION_DB,
    host: process.env.PRODUCTION_HOST,
    port: process.env.PRODUCTION_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      acquire: 60000,
    },
    timezone: '+00:00',
  },
};
