const currentCountries = [
  { countryId: "Indonesia", code: "ID" },
  { countryId: "Nepal", code: "NP" },
  { countryId: "Canada", code: "CA" },
  { countryId: "Argentina", code: "AR" },
  { countryId: "United States", code: "US" },
  { countryId: "Andorra", code: "AD" },
  { countryId: "Colombia", code: "CO" },
  { countryId: "BZ", code: "BZ" },
  { countryId: "NP", code: "NP" },
  { countryId: "india", code: "IN" },
  { countryId: "AL", code: "AL" },
  { countryId: "Azerbaijan", code: "AZ" },
  { countryId: "Egypt", code: "EG" },
  { countryId: "MZ", code: "MZ" },
  { countryId: "VN", code: "VN" },
  { countryId: "Brasil", code: "BR" },
  { countryId: "CA", code: "CA" },
  { countryId: "Bulgaria", code: "BG" },
  { countryId: "Australia", code: "AU" },
  { countryId: "IN", code: "IN" },
  { countryId: "PK", code: "PK" },
  { countryId: "India", code: "IN" },
  { countryId: "GB", code: "GB" },
  { countryId: "Panamá", code: "PA" },
  { countryId: "US", code: "US" },
  { countryId: "Brazil", code: "BR" },
  { countryId: "KE", code: "KE" },
  { countryId: "Angola", code: "AO" },
  { countryId: "AF", code: "AF" },
  { countryId: "BR", code: "BR" },
  { countryId: "Pakistan", code: "PK" },
  { countryId: "Ghana", code: "GH" },
  { countryId: "RO", code: "RO" },
  { countryId: "SA", code: "SA" },
  { countryId: "ليبيا", code: "LY" },
  { countryId: "South Africa", code: "ZA" },
  { countryId: "Honduras", code: "HN" },
  { countryId: "Zimbabwe", code: "ZW" },
  { countryId: "Antarctica", code: "AQ" },
  { countryId: "CO", code: "CO" },
  { countryId: "Nigeria", code: "NG" },
  { countryId: "SN", code: "SN" },
  { countryId: "Jamaica", code: "JM" },
  { countryId: "Germany", code: "DE" },
  { countryId: "Burkina Faso", code: "BF" },
  { countryId: "Russia", code: "RU" },
  { countryId: "Botswana", code: "BW" },
  { countryId: "भारत", code: "IN" },
  { countryId: "España", code: "ES" },
  { countryId: "Türkiye", code: "TR" },
  { countryId: "Philippines", code: "PH" },
  { countryId: "North Macedonia", code: "MK" },
  { countryId: "Ελλάδα", code: "GR" },
  { countryId: "Afghanistan", code: "AF" },
  { countryId: "EG", code: "EG" },
  { countryId: "Algeria", code: "DZ" },
  { countryId: "Netherlands", code: "NL" },
  { countryId: "Bangladesh", code: "BD" },
  { countryId: "Perú", code: "PE" },
  { countryId: "Italy", code: "IT" },
  { countryId: "Albania", code: "AL" },
  { countryId: "Morocco", code: "MA" },
  { countryId: "Iraq", code: "Iraq" },
  { countryId: "DE", code: "DE" },
  { countryId: "বাংলাদেশ", code: "BD" },
  { countryId: "Fiji", code: "FJ" },
  { countryId: "مصر", code: "EG" },
  { countryId: "Tanzania", code: "TZ" },
  { countryId: "Congo-Brazzaville", code: "CG" },
  { countryId: "Kenya", code: "KE" },
  { countryId: "Estados Unidos", code: "US" },
  { countryId: "لبنان", code: "LB" },
  { countryId: "Tunisie", code: "TN" },
  { countryId: "Libya", code: "LY" },
  { countryId: "AD", code: "AD" },
  { countryId: "United Arab Emirates", code: "AE" },
  { countryId: "Antigua & Barbuda", code: "AG" },
  { countryId: "Japan", code: "JP" },
  { countryId: "France", code: "FR" },
  { countryId: "Uganda", code: "UG" },
  { countryId: "Zambia", code: "ZM" },
  { countryId: "Bolivia", code: "BO" },
  { countryId: "Soomaaliya", code: "SO" },
  { countryId: "إسرائيل", code: "IL" },
  { countryId: "Romania", code: "RO" },
  { countryId: "Côte d’Ivoire", code: "CI" },
  { countryId: "Turkey", code: "TR" },
  { countryId: "Togo", code: "TG" },
  { countryId: "American Samoa", code: "AS" },
  { countryId: "अङ्गोला", code: "AO" },
  { countryId: "अल्बेनिया", code: "AL" },
  { countryId: "Armenia", code: "AM" },
  { countryId: "Aruba", code: "AW" },
  { countryId: "अष्ट्रिया", code: "AT" },
  { countryId: "अस्ट्रेलिया", code: "AU" },
  { countryId: "Anguilla", code: "AI" },
  { countryId: "अर्जेंटीना", code: "AR" },
  { countryId: "Åland Islands", code: "AX" },
  { countryId: "Vietnam", code: "VN" },
  { countryId: "Austria", code: "AT" },
  { countryId: "Bahamas", code: "BS" },
  { countryId: "अरुबा", code: "AW" },
  { countryId: "Congo - Kinshasa", code: "CD" },
  { countryId: "कुक टापुहरु", code: "CK" },
  { countryId: "Cape Verde", code: "CV" },
  { countryId: "Mauritius", code: "MU" },
  { countryId: "कोमोरोस", code: "KM" },
  { countryId: "Sri Lanka", code: "LK" },
  { countryId: "Isle of Man", code: "IM" },
  { countryId: "Costa Rica", code: "CR" },
  { countryId: "Congo - Brazzaville", code: "CG" },
  { countryId: "Switzerland", code: "CH" },
  { countryId: "मिस्र", code: "EG" },
  { countryId: "अल्जीरिया", code: "DZ" },
  { countryId: "USA", code: "US" },
  { countryId: "Burundi", code: "BI" },
  { countryId: "AX", code: "AX" },
  { countryId: "AR", code: "AR" },
  { countryId: "BY", code: "BY" },
  { countryId: "DZ", code: "DZ" },
  { countryId: "BA", code: "BA" },
  { countryId: "ID", code: "ID" },
  { countryId: "LY", code: "LY" },
  { countryId: "नेपाल", code: "NP" },
  { countryId: " Canada ", code: "CA" },
  { countryId: "sudan", code: "SD" },

];
module.exports = {
  currentCountries,
};
