const additionalModules = [
      "activation",
      "activity_log",
      "admin_roles",
      "avocado_tree",
      "buying_station",
      "cacao_buyselloverview",
      "carbon_credit",
      "carbon_credit_plot_tree",
      "carbon_credit_projects",
      "carbon_credit_users",
      "coffee_data",
      "compliance_certification",
      "crop_health_report",
      "crops_overview",
      "crops_reports",
      "crops_trace_overview",
      "crops_trace_overview_traceability",
      "dashboard",
      "dds_regional_risk_assessment",
      "deforestation",
      "deforestation_compliance_reports",
      "enterprises",
      "equipment_reports",
      "faq",
      "farm_management",
      "farmers",
      "farmers_reports",
      "farms",
      "farms_reports",
      "goals_achieved_reports",
      "green_beans",
      "land_suitability",
      "manage_offline_farmers",
      "member_data",
      "membership",
      "payments",
      "permissions",
      "pesticides_reports",
      "pests_reports",
      "plantations",
      "regions_reports",
      "report_dashboard",
      "reports",
      "reports_parent",
      "role_requests",
      "survey_builder",
      "tickets",
      "traceability",
      "users/profiles",
      "users/userList",
      "weather_analysis_report",

      //DDS modules 
      "dds_assessment_builder",
      "dds_blends",
      "dds_dashboard",
      "dds_dispute_resolution",
      "dds_due_deligence_guide",
      "dds_due_deligence_report",
      "dds_exempt_product",
      "dds_manage_farm",
      "dds_settings",
      "dds_shipments",
      "dds_suppliers",
      "manage_product",
      "dds_operators",
      "dds_producers",
      "dds_profile",
        
];

additionalModules.forEach(mod => {
  modules.push({ name: mod.replace(/_/g, ' ').replace(/\//g, ' ').replace(/\b\w/g, l => l.toUpperCase()), module: mod });
});

modules.exports = additionalModules;